name: rikulo_el
version: 0.5.0
description: > 
  Rikulo EL is an implementation of the Unified Expression Language 
  specification plus some enhancements for and in Dart.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  unittest:
    sdk: unittest