name: rikulo_el
version: 0.7.0
description: >
  Rikulo EL is an implementation of the Unified Expression Language
  specification plus enhancements for and in Dart.
authors:
- Henri Chen <henrichen@rikulo.org>
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/rikulo/el
dependencies:
  rikulo_commons: any
dev_dependencies:
  unittest: any
environment:
  sdk: ">=1.0.0"
