name: rikulo_el
version: 0.6.0
description: >
  Rikulo EL is an implementation of the Unified Expression Language
  specification plus enhancements for and in Dart.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  js: any
  unittest: any
  rikulo_commons: any
